### ISSUE TITLE
[build:19c03d7d] Can't remove organization

### ISSUE THREAD

**Issue by fallion** [pacedotdev/community#10]
I was testing out how to break up projects to different organisation since private teams are not a feature. 

This meant I created a new organization, but now I'd like to remove it, however no option is present.

**Comment by dahernan** [comment]
sorry is not implemented yet (hopefully you could soon), we can manually delete it for you if you email the org name

**Comment by matryer** [comment]
@fallion We added a new **Manage your org** link to the bottom of the org overview page. You can use it to go to a page where you can schedule your org for deletion. Once you do this, after some time, the org will be removed. Please give it a try and let me know what you think.

**Comment by fallion** [comment]
@matryer works! Thanks! :)
