### ISSUE TITLE
[build:d8d06d29] Can't edit tags

### ISSUE THREAD

**Issue by sipickles** [pacedotdev/community#11]
Need to be able to edit tags, not just delete and recreate. What if I have assigned a tag to many cards?

**Comment by sipickles** [comment]
Personally, I dont think any feature which involves a 'create' operation is ready to ship until it has both delete and edit functionality.

**Comment by matryer** [comment]
@sipickles The way the indexing works, those tags are denormalised (copied). So renaming a tag involves quite an expensive operation. You can change the colour, but the text are like primary key IDs. That's **why** they aren't editable, but agree it's not an ideal user experience. I'll bring this up next week.

**Comment by sipickles** [comment]
Would've thought the text should be an alias for some UUID.

Also I can't see how to change colour of an existing tag.

**Comment by dahernan** [comment]
For now, to change the colour, just create a new one with the same text, and different colour and that will do it

**Comment by matryer** [comment]
Closing, but we added a card in our project to make changing colours easier. Thanks again Simon.
