### ISSUE TITLE
[build:d8d06d29] Can I filter the card view by tag?

### ISSUE THREAD

**Issue by sipickles** [pacedotdev/community#13]
Tags are good, lightweight grouping.

I feel like I need to filter my card view by tag. Maybe I missed it but I dont see how.

**Comment by sipickles** [comment]
FYI I tried putting a tag into the search box, got zero results. #fail

**Comment by sipickles** [comment]
I found it. After I had created enough cards, my FUTURE WORK section had a new link: "There are more, see the full list". By clicking through, I went to a view of all cards where I could filter by tag.

I am pretty sure this link wasn't available before. There needs to be an obvious way to get the to 'All Cards' view.

hth

**Comment by matryer** [comment]
@sipickles Thank you. You can click the headings in each section to get there, but I appreciate the confusion.

**Comment by dahernan** [comment]
tags are also searchable now, thanks for reporting
