### ISSUE TITLE
Github integration - All events look the same in Pace card

### ISSUE THREAD

**Issue by sipickles** [pacedotdev/community#15]
Testing your github integration. Seems to work, and I like the OSX desktop notifications. When I look at the card, I see the same PACE comment for different github events
![image](https://user-images.githubusercontent.com/8441757/84551139-92a54300-ad04-11ea-8f83-72f3acc7f450.png)

This was a PR with a comment and a merge. In Pace I get 5 entries. The push and merge look good, but I didnt get any detail about the comment (eg the comment itself!) and a duplicate 'opened a pull request' entry

**Comment by matryer** [comment]
@sipickles Thanks for reporting this, the GitHub webhooks deliver a lot of information, often duplicated, so we're working on a more robust way to decide what to show.

**Comment by matryer** [comment]
@sipickles we've iterated the design, I wonder if you could try some stuff again and see if it's improved for your use cases?

**Comment by sipickles** [comment]
Looks better, I notice github comment contents are properly reflected in Pace now. Thanks @matryer

**Comment by matryer** [comment]
Thanks go to @dahernan :)
