### ISSUE TITLE
[build:d8d06d29] Only some cards show tags in side bar

### ISSUE THREAD

**Issue by sipickles** [pacedotdev/community#16]
All these cards have tags, but only 2 show them in the sidebar:

![image](https://user-images.githubusercontent.com/8441757/84552708-c8005f80-ad09-11ea-8f8d-900f78cd3054.png)

**Comment by matryer** [comment]
Thanks for reporting. This happens because updating the tags doesn't trigger an update in the inbox. I think it should.

**Comment by dahernan** [comment]
it should work now #pace295

**Comment by sipickles** [comment]
@dahernan Sorry still a problem in 06e80cb5

**Comment by dahernan** [comment]
you need to trigger an update on the card, we did not reindex the whole database, add and remove a tag for example

**Comment by sipickles** [comment]
Sorted, thanks
