### ISSUE TITLE
[build:f3ec771e] Feature request: Tell me if I can change my org name

### ISSUE THREAD

**Issue by t-eckert** [pacedotdev/community#18]
## Feature request

When creating a new org, I would like to know whether or not I will be able to change the name in the future. If I can, having a little note "You can change this in the future", or otherwise "This is permanent, choose wisely", would help me feel more confident about choosing an org name.

Great work! Loved hearing you on JS Party! Excited to check out the product!

**Comment by matryer** [comment]
This is fair enough. The Org IDs are fixed, but org names could change in the future. @dahernan Let's think about this one.

**Comment by matryer** [comment]
Fixed.
