### ISSUE TITLE
[build:c65c68e0] Any way to delete cards?

### ISSUE THREAD

**Issue by sipickles** [pacedotdev/community#19]
When we joined pace, one of our team added a few test cards. We'd like to remove or hide them as they are noise amongst the real work items. I can't see a way.

**Comment by dahernan** [comment]
Edit -> Delete Card

**Comment by dahernan** [comment]
We should add some videos of common flows soon, but it should be more obvious.

**Comment by sipickles** [comment]
ok, it is kinda obvious now you mention it, however I can't delete cards if someone else created them. This would be a problem if someone left a project. As an admin (project owner) I would expect to have super powers.

**Comment by dahernan** [comment]
anyone is able to delete cards that you didn't create, no matter if you are an admin or not, we did not implement any check on that, if you have a problem deleting other people cards, please let us know

**Comment by sipickles** [comment]
@dahernan I get this message in an angry red :)

"you can only delete your own messages"
