### ISSUE TITLE
[build:eaa570a1] Timestamps in Conversation titles render in GMT by default

### ISSUE THREAD

**Issue by brainsnail** [pacedotdev/community#2]
The timestamp next to the user name looks good though. In this case it was PST yesterday afternoon (GMT -7). 

Example:
<img width="391" alt="image" src="https://user-images.githubusercontent.com/444193/84285373-3f5ba680-aaf2-11ea-8dc4-8a578f7bab0e.png">

**Comment by dahernan** [comment]
nice catch!, I was testing different timezones last week and i didn't notice, we will solve it soon

**Comment by matryer** [comment]
This is because that time is decided on the server, and not in the client. Thanks for reporting @brainsnail :)

**Comment by matryer** [comment]
@brainsnail We have changed the way this works a little, and I wonder if you could test it for us? We no longer create that default title, and in fact don't show it up in the inbox on the left until you have saved it.

Can you please do a hard refresh (Cmd+Shift+R on a Mac) and try it out for us?

**Comment by brainsnail** [comment]
@matryer Looks perfect now. 

I did the following : 
- Created a new conversation
- Typed something in the conversation body 
- Attempted to navigate to an existing card on the left nav bar and was blocked by validation in the title (yay)
- Attempted to save the conversation and was blocked by validation in the title (double yay)
- Saved the conversation

👍  Thanks!
