### ISSUE TITLE
[build:f9f95b08] Permalinks for comments please

### ISSUE THREAD

**Issue by kinbiko** [pacedotdev/community#20]
These are useful for larger teams/cards where you'd like to point someone to a decision/some information that was provided way back when.

**Comment by matryer** [comment]
@kinbiko Thanks for this. I agree, sometimes you want to point to specific things and perma-links are a nice way to do that. (Every comment gets its own ID so it's just a UX exercise for us).

On top of that, I wonder if you could tell me _why_ you're pointing to comments? We have some other ideas which we think might help highlight the gold within a conversation, so would very much appreciate it if you could expand a little on your use cases?

**Comment by kinbiko** [comment]
@matryer

Off the top of my head:

1. Showing new joiners technical decisions that had been made in the past for context around something weird they stumbled upon in a 3rd-party platform like on a GitHub pull request.
1. Reminding people to reply to a question asked on another thread when they're communicating synchronously in a conference call etc.
1. Anonymously referencing offensive behaviour from a team member in a report to a manager.

**Comment by matryer** [comment]
Adding this to our Future work for consideration.
