### ISSUE TITLE
[build:f9f95b08] Quick create related card goes missing once there's already a related card linked

### ISSUE THREAD

**Issue by kinbiko** [pacedotdev/community#21]
After playing around a bit I discovered that you can get the 'create related' button back by 'x'-ing out the search field, but this was not obvious. Would be good to have the button for creating related cards still visible when searching for existing cards.

**Comment by matryer** [comment]
Hmmm, @kinbiko that sounds completely reasonable. We'll take a look. Thanks.

**Comment by matryer** [comment]
@kinbiko We changed it today so the buttons remain visible, do you think this works better? 

* It is deployed live to https://pace.dev/app 

![image](https://user-images.githubusercontent.com/101659/85028715-54c87480-b173-11ea-866c-58b6362f5acd.png)

**Comment by kinbiko** [comment]
@matryer 

Just had a play around with it and it looks good!
I like how it keeps the search when switching between the 'Create related' and 'attach existing' too.
Amazing turnaround!
