### ISSUE TITLE
[build:f9f95b08] Relationships are not symmetric

### ISSUE THREAD

**Issue by kinbiko** [pacedotdev/community#22]
If I link card A to card B, then I'd expect a symmetric relationship from B to A.

**Comment by matryer** [comment]
@kinbiko We've done some work on this today. We have exposed the inverse relationship (children to parents). Please check it out at https://pace.dev/app and let us know if this is clearer.

**Comment by kinbiko** [comment]
Nice! That solves my problem.
Not sure if having a directed relationship like this (`PART OF…` and `RELATED CARDS`) can cause some confusion (A card can currently be it's own grandcard, if we use the child/parent analogy), but I don't mind too much. As a user I can make up my own mind of how to use these relationships.
