### ISSUE TITLE
[build:f9f95b08] Align statuses horizontally

### ISSUE THREAD

**Issue by kinbiko** [pacedotdev/community#23]
Horizontally aligning statuses on drag and drop is friendlier as there's usually more real-estate both on the screen and on the mouse pad/trackpad for moving horizontally.

**Comment by matryer** [comment]
@kinbiko we've designed a deliberately non-trello style overview, showing the most important information at the top (in progress, the up next, etc). This is a different approach to other tools, so please give it a go and let me know what you think.

**Did you know?** you can use the little menu dots on the card to change their status also.
