### ISSUE TITLE
[build:f9f95b08] Unintuitive ordering of statuses

### ISSUE THREAD

**Issue by kinbiko** [pacedotdev/community#24]
I don't know if this was intentional, but intuitively I'd expect cards to move more or less in a single direction direction, i.e. `Future work` -> `Up next` -> `In progress` -> `Done`.
Right now I'm seeing `In progress` -> `Up next` -> `Future work` -> `Done` (reading from top to bottom).

**Comment by matryer** [comment]
@kinbiko Thanks for raising this. We've prioritised information based on what we think is most important to teams, rather than the workflow of the cards. So we have In progress at the top, because it's the current focus of the team. Then what's next is most important.

We realise this breaks from most Kanban style tools but we hope it encourages people away from the mindset of just churning through an ever growing list of work.

What do you think?

**Comment by kinbiko** [comment]
@matryer 

That is certainly novel, and I think you're onto something when it comes to emphasising the importance of finishing work over perceived progress (if I get what you're saying).

I am by no means a designer, so take what I'm about to say with a mountain of salt.
As this is different to most kanban tools, I can imagine many people reacting in the way I did.
Not having cards move in contiguous stages means I have to re-orient myself whenever I go back from moving something from 'In progress' to 'Done'. This mainly applies when moving several tickets.

I wonder if the notion of importance can be visualised in other ways (colours, size, etc) whereas visualising process (not necessarily progress) is most easily done by having a flow of sequential stages.

**Comment by matryer** [comment]
@kinbiko yeah that's interesting feedback for sure. We are thinking about ways we can let people group tasks up in more interesting ways. We'd love to hear more examples of the types of groupings you'd do; importance is one (so cards 1, 2, and 3 are all more important than the rest?) Anything else spring to mind?

**Comment by kinbiko** [comment]
Based on what I've seen IRL (taken from a **union** of several teams, not the **intersection**):

- stack/component/specialty/whatever you wanna call it. E.g. "Frontend"/"Backend", "user-service".
- project (e.g. "dashboard redesign")
- target release(date) (e.g. "v1.5.2")
- sprint (e.g. "2020 - Sprint 20")
- priority (e.g. "high"/"medium"/"low")
- urgency (subtly different to importance. E.g. "immediate", "today", "this sprint", "this quarter")
- "feature" or "maintenance"

One problem I've seen IRL is trying to fit a large structure to many teams, and ending up with dozens of fields like the above, which ends up being bloated (most teams only use a few).

My personal, ideal scenario would be to have a system of user-defined labels of the form `label:value`, e.g. `release:v1.5.2`, `flow:in-review` or `project:dashboard-redesign` then being able to group at will by the `label` before the `:`. Power to the people instead of the tool. Almost like an evolution to the tags you've got currently.

Obviously, I've only spent a single-digit number of calories thinking about this...

**Comment by matryer** [comment]
😂 Well they were calories well spent. @tomwilkie actually mentioned that same approach to tags when I chatted to him about this a few months ago, and I must admit it does appeal. One big issue we want to avoid is the potential mess that _could_ be created by abusing (albeit with the best intentions) a system like that. (We want to keep our ux as minimalist as possible etc)

But I can see something like this working quite well. 

@dahernan What do you think of tags like these:

* `project:dashboard-redesign`, `project:backup`, `project:planning-tool`
* `app:pace`, `app:machinebox`, `app:facebox`

**Comment by dahernan** [comment]
We can explore that approach, maybe if we use it we can understand it better

**Comment by matryer** [comment]
Closing as this question was answered.
