### ISSUE TITLE
[build:f9f95b08] Card creation click count nit

### ISSUE THREAD

**Issue by kinbiko** [pacedotdev/community#25]
This is such a nit of a problem...

Right now, to create multiple cards in a row, it’s 'Add Card' -> 'Create' -> 'close' (or click ‘Add card’ tab again) -> Add card.
I think it would help ux if there was a text box for entering the next card title after clicking ‘Create’, without the need to close anything.

**Comment by matryer** [comment]
@kinbiko Thanks for this - we've heard this elsewhere too, so it is something we'll look at.

**Comment by matryer** [comment]
@kinbiko For testing and playing around, creating lots of cards is useful. But what about in the real world? Does your workflow have you creating lots of cards one after the other usually?

**Comment by kinbiko** [comment]
@matryer Yes. Two most common use cases:

1. I've just finished a design and I've got a pretty good idea of how to break down the most immediate bit of work based on the design. I'll create these cards right after each other while I still have the same context in my head (and more often than not, the same link to the design in my clipboard).

1. I need to do the same work for multiple components (microservices usually). I then create one card, and copy all the title/contents to my clipboard and edit 1 or 2 words per card.

That is, that's the workflow I use in J***. It could well be that it would change with Pace.

Another example that I can think of, but can't claim personal experience with, would be raising bug reports for the same release (parent card) following the results of QA.

Hope that helps.

**Comment by matryer** [comment]
@kinbiko We've tried a subtle change in the card composition component. So now, after you create a card, the box stays open with the cursor in place ready for the next one. We want to encourage more careful card writing (i.e. with the right amount of detail in the body, etc.) but understand the need to sometimes just quickly create three or four things, and then go back and add the detail after. Please do a hard reload of the app and let me know what you think of this change.

**Comment by kinbiko** [comment]
@matryer Just checked it out, and the workflow is super smooth! 0 context switching. Love it

**Comment by matryer** [comment]
Thanks @kinbiko.
