### ISSUE TITLE
[build:f9f95b08] This looks awesome

### ISSUE THREAD

**Issue by kinbiko** [pacedotdev/community#27]
This ticket is not a bug. It is just love.

I've raised a lot of issues on this repo recently, so pardon the spam, but I'm very excited to start using this tool for my private projects! It is super clean and even has some features I didn't know I wanted (conversations and showcasing for example)!

Great job!

**Comment by matryer** [comment]
Thanks @kinbiko - we took your issues in the spirit they were intended. And they're very helpful. Let's stay in touch.
