### ISSUE TITLE
[build:06122bee] VAT ID should be optional

### ISSUE THREAD

**Issue by fallion** [pacedotdev/community#28]
In Billing VAT ID cannot be left empty, however not all business have VAT IDs yet.

**Comment by dahernan** [comment]
Yeah that's true, but I believe if you don't have it we need to charge you the taxes, is something that we have to verify

**Comment by fallion** [comment]
Thank you, let me know if/when this gets verified.

**Comment by matryer** [comment]
Moving to email.
