### ISSUE TITLE
[build:5224e8a6] - Signup

### ISSUE THREAD

**Issue by sekchai2** [pacedotdev/community#29]
Platform: MacOS 10.15.5
Browser: Safari

Account sign up with Google

On first sign-up, I am prompted to select Google account.  After selecting account, I am redirected back to https://pace.dev/app/.   There is no notification that an account was created or verified.     I have to RE-select sign-in to enter application.

**Comment by matryer** [comment]
Hey @sekchai2 That sounds very strange. I wonder if it's just a blip in the internet. Please let me know if anything like this happens again.
