### ISSUE TITLE
[build:29a1754f] Keyboard shortcuts

### ISSUE THREAD

**Issue by ngrilly** [pacedotdev/community#3]
Do you plan to provide keyboard shortcuts? That would be especially useful to enter multiple cards and manage the backlog.

**Comment by dahernan** [comment]
Yes, is on the "Up Next", but we have no much idea which one would be useful at this stage, we are using Pace to build Pace, so probably that common patterns for shortcuts would clarify soon

**Comment by matryer** [comment]
@ngrilly What keyboard shortcuts would you like to see? What operations do you do most often?

**Comment by matryer** [comment]
@ngrilly we added Ctrl+h for home, and ctrl+f to jump to search box. Can you try them and let us know what you think? Help can be found by pressing `ctrl+shift+/`

**Comment by ngrilly** [comment]
@matryer Nice! Tested. It works. Maybe Ctrl should be Cmd on Mac? And display/hide help using just "h" or "?"?

> What keyboard shortcuts would you like to see?

Create one card or multiple cards in a row. Something like Ctrl+Enter to save. Navigate between cards.

**Comment by matryer** [comment]
OK I've updated it. Following the suggestion from @ngrilly I've simplified the keys to not require any `shift` or `ctrl` keys. So now `?` show/hide help, `h` will go to the homepage, and `f` will jump to the search box.

**We'll keep this a hidden feature for now**, but do let me know if any other ideas occur.

**Comment by matryer** [comment]
@ngrilly Do the basic mechanics work as you expect now? If so, we can consider other shortcuts that would be useful.

**Comment by matryer** [comment]
Closing until we have more firm use cases for additional keyboard shortcuts. Note: the ones discussed here are live.
