### ISSUE TITLE
[build:784fb1e1] Team member status date bug

### ISSUE THREAD

**Issue by sipickles** [pacedotdev/community#31]
I like the slightly quirky feature where you get a slideshow of each team member's status.

One small bug in the time stamp. It says "Jun 13 ago". Looks like a mix between a relative and absolute date.

Hardly a showstopper but hth

**Comment by matryer** [comment]
thanks @sipickles - you're right; it's a bad bit of code evolution.

**Comment by matryer** [comment]
Fixed. Thanks again.
