### ISSUE TITLE
[build:c819a2ba] Thumbnail pics after upload

### ISSUE THREAD

**Issue by sekchai2** [pacedotdev/community#35]
Annoyance

After upload of a new profile pic and commenting, the previous thumbnail picture is shown in browser.

This is not a problem for other users, but the original user's browser shows old thumbnail. (Clearing browser cache fixes this but is a manual step)

**Comment by dahernan** [comment]
Yeah we do cache it for around 24 hours, we will have a look to boost the cache for current user

**Comment by matryer** [comment]
@sekchai2 We have implemented a solution for this, I wonder if you could try it now and verify?

(To get the latest version, do a hard reload)

**Comment by sekchai2** [comment]
Just saw this comment.  Now that billing is implemented and my trial expired I am unable to test.

Looks like I have additional test time..

Re-tested and thumbnail is now updated after upload
