### ISSUE TITLE
[build:c819a2ba] Uploaded mov to showcase, not compatible?

### ISSUE THREAD

**Issue by sipickles** [pacedotdev/community#36]
Hi,

Added a small 300k movie screen recording to the showcase and it wont play. Mov was recorded with QT player on OSX Mojave.

Part of URL to showcase (rest removed for privacy): 5efdd98008cf9c0b

**Comment by matryer** [comment]
@sipickles We rely on browser support to decide which videos can be played and which cannot. Recording via Quicktime will likely require some transcoding etc. which is beyond the scope of our video support for now. If you record the screen via the option in the comment's box in Pace, does that work?

**Comment by sipickles** [comment]
Yes, thats fine, although it lacks the ability to record a portion of your screen AFAIK.
