### ISSUE TITLE
[build:792971ab] How do I express that work is 'No longer required'

### ISSUE THREAD

**Issue by sipickles** [pacedotdev/community#39]
Whats the rationale behind not providing a card state of 'No Longer Required'?

Cards are often outdated or duplicates, so a should not be considered future work, but are also not 'Done'. You might not want to delete them too.

Some sort of No Longer Required state would be useful.

**Comment by matryer** [comment]
@sipickles This was an area we've discussed a lot in the past. We found that we _never_ went back to resurrect old cards and very rarely needed that information. Often, by the time the work became relevant again, enough had changed that made the original thinking pretty useless, or if somebody else was picking up the work, they might have been discouraged them undertaking their own discovery process. **So we opted instead to delete old data.** This has the added benefit of keeping search indexes cleaner, and the UX less cluttered. 

What do you think?

**Comment by sipickles** [comment]
Its unorthodox but I'm willing to try.
