### ISSUE TITLE
[build:07082832] : inactive input box on `Welcome to the Pace`

### ISSUE THREAD

**Issue by dolanor** [pacedotdev/community#4]
On the `Welcome to the Pace` message, there is a `include someone or a team` button + input text.
I can input something, but nothing pops up (as suggestion), and pressing `enter` doesn't do anything.
What is it supposed to do?

**Comment by dahernan** [comment]
you could include people from your org, but when you are the only one you can not include anyone. We have to improve that state to be less confusing.

**Comment by matryer** [comment]
@dolanor Thanks for reporting this. We'll definitely work to make this clearer.

**Comment by dolanor** [comment]
Maybe a popdown widget saying: `looking for people in your org` (like when you search in github, there is the popdown saying `in this repository`)

**Comment by matryer** [comment]
@dolanor we've redesigned this section a little to make it easier to use based on your feedback. Can you please do a hard refresh (`Cmd+Shift+R` on a Mac) and try it out for us? The build tag (bottom left) should be `19c03d7d`.

**Comment by dolanor** [comment]
It works for me, but again, being new, I didn't know it would only look for people in my org. That info could be added in the infobox under so we can learn from it.

**Comment by matryer** [comment]
![image](https://user-images.githubusercontent.com/101659/84590408-2c1c4400-ae2e-11ea-81ed-b0e07ce7ec37.png)

@dolanor How about this? Does it make clear that you're searching within the org? (My org is called NEW ORG LOOK).

**Comment by dolanor** [comment]
I like the look of it now, thanks!
