### ISSUE TITLE
[build:792971ab] Deleting a headline showcase item leads to a permanent gap

### ISSUE THREAD

**Issue by sipickles** [pacedotdev/community#40]
Repro (I think):

* Create 4 showcase items (1,2,3,4). The first 3 are shown on the project landing page, 4 is hidden.
* Delete one of the first 3 showcases, eg 2.
* Expected behaviour: The landing page shows 1, 3 and 4.
* Actual Behaviour: The landing page shows 1 and 3 and a gap. To see 4 I have to use the 'View all showcases' option

Note, adding a new showcase does not fix the gap (but I think it might shuffle along)

**Comment by dahernan** [comment]
Simon, thanks for pointing this out. You were right, we found the problem and we've fixed it. If you refresh, you shouldn't have the same problem again.
