### ISSUE TITLE
[build:930ea576] Trial Expiration by Org?

### ISSUE THREAD

**Issue by sekchai2** [pacedotdev/community#41]
I have three Org's created under pace.dev/app.

Since they were created on different days/times, two of them says in the banner that I have 5 days left.   One of them has the message:

Your free trial has expired, please ask an administrator to set up billing to continue.

----

This is an odd behavior because it feels like I would be paying for any amount of orgs but limited by number of users in the system. (per month/per user).

**Comment by matryer** [comment]
Hi Sek.

In Pace, billing works per-org, and you create multiple teams within that to group people up.

I hope this helps.
Mat
