### ISSUE TITLE
[build:3c6f2408] pushing to a PR causes second Github event

### ISSUE THREAD

**Issue by fallion** [pacedotdev/community#43]
When creating a PR which references a pace issue it would be great if only one reference was created back in pace. 

Right now the `send everything` setting in webhooks will trigger when a PR is updated and pace reacts to this by linking it again.

Steps to reproduce:
- create PR without issue reference
- edit PR to add issue reference (links it in pace)
- push new commit to the PR (in my case force push)

Thanks :)

![image](https://user-images.githubusercontent.com/683286/87529777-c66ee200-c68f-11ea-861e-dd1f11505d12.png)

**Comment by dahernan** [comment]
thanks, we'll have a look. I fixed something similar few weeks ago, but github webhooks are tricky :(

**Comment by dahernan** [comment]
it should be different event now
