### ISSUE TITLE
[build:3c6f2408] link to an issue

### ISSUE THREAD

**Issue by fallion** [pacedotdev/community#44]
I'm setting up the auto-link setting in Github for easy back and forth between the two systems. 

What is the preferred way to link directly to an issue? Right now I found the easiest way to go https://pace.dev/app/org/c/link/5 as the `link` part is ignored. Are there any possible issues with this?

**Comment by dahernan** [comment]
Yes that should be ok, but we usually leave the card title empty with `-` for example https://pace.dev/app/org/c/-/5 that would be populated with the real slug when you access that link
