### ISSUE TITLE
Breakdown is confusing

### ISSUE THREAD

**Issue by vorcigernix** [pacedotdev/community#45]
So if you work in some regular product development, you get a feature/product improvement and first thing you do is that you break this to the smaller work fragments (stories/tasks). This logic seems to be missing and when I tried to create a related tasks, it just got confusing and I can't imagine working in this visual system. 
You may have some different flow in mind, but it was not clear to me. Perhaps if you create a sample board with your project, it may help me to understand the way you work on the bigger work fragments.

**Comment by matryer** [comment]
@vorcigernix Thanks for your question. We'd love to set up a time to have a quick 15-30m chat about your workflow, if that's something you'd have time for? In particular, we want to understand your workflow, how the higher-level pieces are decided, and how that translates to work for devs. If you're interested, please email us hello@pace.dev.
