### ISSUE TITLE
[build:596a9148] - Cannot sign on

### ISSUE THREAD

**Issue by ayang64** [pacedotdev/community#46]
# Problem

Cannot sign on using OAuth.  When I attempt to sign on, i get the message:

```
Sorry, we couldn't sign you in
This browser is not supported or 3rd party cookies and data may be disabled
```

I'm using `Chromium Version 83.0.4103.116 (Official Build) (64-bit)` under FreeBSD (`FreeBSD 13.0-CURRENT #13 c62675ffb32-c269902(master)`)

# How to reproduce

Install FreeBSD, install Chrome, & attempt to sign on.

**Comment by dahernan** [comment]
Can you open the developer console and see if there are any errors? I have 2FA without any problems in Chrome

**Comment by ayang64** [comment]
Nothing appears in the dev console.  I also tried in Incognito mode without my fancy plugins -- still fails.

**Comment by ayang64** [comment]
Sorry -- false alarm. I configured Chrome to block 3rd party cookies. :(  Sorry for the trouble.

**Comment by dahernan** [comment]
cool, sorry firebase auth put more cookies that it should, we could review if it's possible to trim them
