### ISSUE TITLE
What is status intended for?

### ISSUE THREAD

**Issue by dzajic** [pacedotdev/community#47]
Maybe this could go in an FAQ, along with other common questions.

**Comment by matryer** [comment]
Hey @dzajic - your status shows up on that team page, to let your team mates know what you're focussed on. Some teams don't have daily calls, or they don't work at the same time, so this can be useful for keeping everyone up to date.

**Comment by dzajic** [comment]
I see, yeah, that does seem useful. Do you think it takes up too much space or should be collapsable? I do think it's cool to be able to see larger photos, to get a more in-person feel for distributed teams (we all are right now, anyway), but maybe having the option to hide/minimize would be nice for people that want to see more cards by default.
Also, maybe the status could be shown on hovering over the smaller team icons that are above that. That would further reduce the need to have it take up so much space. (Though that won't work on mobile, but the issue will be even worse there.)
For now I'll just set up some custom CSS using Stylus for Firefox. Thanks for the reply!
