### ISSUE TITLE
[build:f945368f] cards view ?

### ISSUE THREAD

**Issue by menems** [pacedotdev/community#49]
Hi, functional question 

What is the /card view goal?

is a priority macro view?

Why not a simple list instead of a "keep like" view?

Maybe add relational line between card can explain this kind of view.
and maybe the order of card depends of this related tree of card ?

**Comment by matryer** [comment]
Hey @menems - I'm not sure what you mean by the /card view? Can you elaborate a little?

**Comment by matryer** [comment]
Closing because I failed to understand this. @menems reopen if you like :)
