### ISSUE TITLE
[build:89d03bf8] JSON.parse error when creating a team 

### ISSUE THREAD

**Issue by vladimir-ch** [pacedotdev/community#5]
After creating an org, I went to create the first team. The creation took several seconds and then seemingly failed with the following error in red:
```
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
```
The page didn't change, it still showed the form for inputting a team name. However, after going to the main org page the team appeared as existing. I didn't get this error again when creating more teams. On the org page the formatting of the first team is different: instead of my Google avatar only the word Team appears.

**Comment by dahernan** [comment]
Thanks for reporting, you'll probably hit a spike of latency when one of the servers started, I'm reviewing the config to get better experience when that happens

**Comment by dahernan** [comment]
we improved the first request latency, it should not happen anymore
