### ISSUE TITLE
[build:9a0aed82] Stale cards/titles on board

### ISSUE THREAD

**Issue by dzajic** [pacedotdev/community#50]
Cards show outdated title on the board after renaming. Card view shows the correct title.

(FTR deleting the pacedb-cache/cachedata resolves the issue.)

**Comment by dahernan** [comment]
Maybe connectivity issue? The update should happen in realtime, and the cache should be updated. You can try to edit a card in a tab and the other tab with the team view should have the update

**Comment by dzajic** [comment]
Doubt that, my Internet connection is rock solid, but the issue isn't consistent. I just updated a title and it did correctly update on the board. Maybe the cache should expire daily just in case? Not sure, but I can close this and reopen if I see it happen again.

**Comment by dahernan** [comment]
No problem, we'll keep an eye on it

**Comment by dzajic** [comment]
I just saw another instance of this, when I marked a card as "Done", and it's still showing as "In Progress" on the board. I'm using Firefox, FTR.

**Comment by dzajic** [comment]
I think it could be a race-condition. I am probably clicking away from the page too quickly after clicking "Done". I just toggled the status to "In Progress" and back to "Done", waited a bit, then went to the board and it was gone this time.

**Comment by dahernan** [comment]
ok, thanks for the explanation, we will review it

**Comment by matryer** [comment]
@dzajic Thanks for reporting this. Next time you see it, can you do me a quick favour and check the board in a different browser? I want to figure out if it's the in-browser cache that's misbehaving, or something server-side. And also, see if there's anything interested in the Web Console in Firefox?

**Comment by tessellator** [comment]
I am seeing this issue in Firefox too. It appears that the statuses of my cards are stale only on the team page (/t/team-name), but if I look at card details or the cards view (/t/team-name/cards), the statuses are correct.

I checked in Safari and Firefox Dev Edition and the cards appear correctly in all three views. I had not logged into the app with either of those browsers before experiencing the issue in my primary Firefox browser.

Unfortunately I cannot recall my last actions that might have led to this state.

Is there anything I can test for you on my end?

**Comment by dahernan** [comment]
We disabled the local cache in the team view for now, so it shouldn't happen again. We will enable again when we reproduce the issue and we can debug it.

**Comment by tessellator** [comment]
Thanks - I logged in and see that the cards are reflected correctly on the team page now. Really enjoying the product. :)

**Comment by dahernan** [comment]
Closing for now, it seems stable now
