### ISSUE TITLE
Support Markdown tables [build:9a0aed82] 

### ISSUE THREAD

**Issue by kinbiko** [pacedotdev/community#52]
I was hoping that I could use Markdown tables in a discussion, but it was rendered as pure text.
Even when pretty-printed in a monospaced font and wrapped in code blocks, the line-wrapping makes it render horribly.

**Comment by dahernan** [comment]
I see, for some reason I though it was supported, let us some time to review it

**Comment by dahernan** [comment]
They are not brilliantly render, but are supported.

<img width="468" alt="Screenshot 2020-09-02 at 20 15 09" src="https://user-images.githubusercontent.com/615811/92026544-1ba6a600-ed59-11ea-89eb-71b0a9d9b6e2.png">
<img width="464" alt="Screenshot 2020-09-02 at 20 15 00" src="https://user-images.githubusercontent.com/615811/92026547-1c3f3c80-ed59-11ea-985e-b80c6e8888ad.png">

Can you provide an example?

**Comment by kinbiko** [comment]
Oh, yeah, you're right. It just rendered so awkwardly by default that I thought it wasn't supported.

```
| DB                        | Ramp-up time | Performance                          | Initial Cost | Usage       | Development Speed | Go Support    | Maintenance                             |
| ------------------------- | ------------ | ------------------------------------ | ------------ | ----------- | ----------------- | ------------- | --------------------------------------- |
| MongoDB                   | Minimal      | Good                                 | Free         | General     | Fast              | Adequate      | No referential integrity.               |
| ElasticSearch             | Some         | Great, for a few use cases           | \$16/mo      | Search-only | OK                | No experience | No referential integrity. Not reliable. |
| Neo4J                     | Considerable | Uniquely great, for a niche use-case | \$64/mo      | Graph-only  | OK                | Unknown       | No experience.                          |
| PostgreSQL (or other SQL) | Considerable | Excellent                            | \$9.96/mo    | General     | OK                | Good          | No experience.                          |
```
(ignore the actual contents 🙂 )

![image](https://user-images.githubusercontent.com/8797880/92061019-3b2ce580-edd0-11ea-816f-b899876ea0e4.png)

It would be a lot clearer if there were indications of what the grid was.
Compare the above with how GitHub does it:

| DB                        | Ramp-up time | Performance                          | Initial Cost | Usage       | Development Speed | Go Support    | Maintenance                             |
| ------------------------- | ------------ | ------------------------------------ | ------------ | ----------- | ----------------- | ------------- | --------------------------------------- |
| MongoDB                   | Minimal      | Good                                 | Free         | General     | Fast              | Adequate      | No referential integrity.               |
| ElasticSearch             | Some         | Great, for a few use cases           | \$16/mo      | Search-only | OK                | No experience | No referential integrity. Not reliable. |
| Neo4J                     | Considerable | Uniquely great, for a niche use-case | \$64/mo      | Graph-only  | OK                | Unknown       | No experience.                          |
| PostgreSQL (or other SQL) | Considerable | Excellent                            | \$9.96/mo    | General     | OK                | Good          | No experience.                          |

Note: the markdown hint doesn't mention that tables are supported either.
![image](https://user-images.githubusercontent.com/8797880/92061254-c3ab8600-edd0-11ea-9621-ae73fc48402f.png)

**Comment by matryer** [comment]
@kinbiko deployed a fix... would you be able to test it for me and see if it looks better for you? Hard reload should do it.

**Comment by kinbiko** [comment]
Don't really think it looks all that much better. Only difference I could find was that if the table was wider it would scroll horizontally (you can tell by the tiny bit of text clipped on the RHS)

![image](https://user-images.githubusercontent.com/8797880/92249683-6c5b0200-ef05-11ea-8492-1e63fc29c800.png)

Commit: fa0dcb0a

**Comment by kinbiko** [comment]
Oh! I tried opening it in Chrome, and it looks a lot better now!
The above screenshot was taken on vivaldi. I thought it would render the same way that chrome does, seeing as it's chromium-based, but I guess not.

Feel free to close.

**Comment by matryer** [comment]
It doesn’t look like it’s updated. I’ve cleared out our caches. How do you
do a hard reload on your browser? On Chrome on Mac it’s Cmd+Shfit+R.

**Comment by kinbiko** [comment]
Yeah, I did the hard reload several times before taking the above screenshot.

Anyway, now it looks fine on Vivaldi too.
If I were to guess, GCP probably doesn't clear it's caches immediately from all its locations, and I live on the other side of the planet to where you're located.
I'll keep that in mind before checking updates to future issues I raise 👍 

Anyway, can probably close this one now.

Thanks for the quick turnaround!

**Comment by matryer** [comment]
Thanks Roger.
