### ISSUE TITLE
[build:fa0dcb0a] Feedback from first use.

### ISSUE THREAD

**Issue by alexellis** [pacedotdev/community#53]
Having seen Matt talk about the code for Pace, I wanted to try it out.

Here is some feedback from my first use. Hope it's of some use to you.

On the "Add card menu"

> "Enter a brief title"

This confused me as a new user. I read it as entering a brief. I just wanted to "Add card"

Maybe just "Card title"

It felt odd that I had to create a team and a company to use the tool. I would imagine you will attract users who are solo or personal users. It would be nice if they didn't have to make up a fictitious company name to add a card.

**Comment by alexellis** [comment]
It seems odd that I can't delete a card unless I click "edit". This was confusing and non-intuitive for me vs. other tools

**Comment by alexellis** [comment]
I am finding the dark theme quite hard to see - it's mainly the light dark text on a dark grey background. I'd suggest using higher contrast and using a light theme by default. I also can't see where to hit the "lightbulb" icon?

For feedback, I'd rather send comments through the UI than open a github issue - these are too public and too burdensome for UX feedback.

**Comment by alexellis** [comment]
In order to enter text for a card I have to find and click edit. I'd rather the description was a larger empty space or said "Click to edit" since this is the obvious next action for me.


<img width="630" alt="Screenshot 2020-09-13 at 17 56 09" src="https://user-images.githubusercontent.com/6358735/93023936-70181400-f5ea-11ea-8cbf-8c657c41193e.png">

<img width="636" alt="Screenshot 2020-09-13 at 17 56 13" src="https://user-images.githubusercontent.com/6358735/93023932-6ee6e700-f5ea-11ea-9deb-95f373bfcc9b.png">



Even better if Add card could accept a description

I'd also be very pleased if clicking the title would turn the element into a textbox and start an edit flow.

<img width="634" alt="Screenshot 2020-09-13 at 18 02 40" src="https://user-images.githubusercontent.com/6358735/93024075-680ca400-f5eb-11ea-85b8-cdc084914f5c.png">


<img width="338" alt="Screenshot 2020-09-13 at 17 57 16" src="https://user-images.githubusercontent.com/6358735/93023965-92aa2d00-f5ea-11ea-8246-68a3c82fb25e.png">


"Add card" is not highlighted when clicked. This makes it hard for me to know what I'm doing and the result of entering text.

**Comment by alexellis** [comment]
I wasn't able to get markdown lists working as expected?

<img width="642" alt="Screenshot 2020-09-13 at 17 59 00" src="https://user-images.githubusercontent.com/6358735/93024005-d735c880-f5ea-11ea-9d8d-ae8108365572.png">

<img width="644" alt="Screenshot 2020-09-13 at 17 58 54" src="https://user-images.githubusercontent.com/6358735/93024006-d7ce5f00-f5ea-11ea-8d60-df3511eead55.png">

GitHub markdown result:

Roadmap items:
* Proxy any TCP port in the list of ports against a docker-compose service
* Add container limits for CPU + memory

**Comment by alexellis** [comment]
I'm not sure it's that useful to set a reaction to actions I took.

<img width="599" alt="Screenshot 2020-09-13 at 18 04 26" src="https://user-images.githubusercontent.com/6358735/93024106-a7d38b80-f5eb-11ea-8c49-75fc6ba344f5.png">

**Comment by alexellis** [comment]
<img width="952" alt="Screenshot 2020-09-13 at 18 06 47" src="https://user-images.githubusercontent.com/6358735/93024151-1add0200-f5ec-11ea-86fc-991496af4ca6.png">

The status seems to follow a left to right flow, but is presented as a horizontal list which takes up significant space and is hard to notice.

Having it above or below the card would be easier to notice and update. I had to search for this to see why it wasn't showing up in the "In Progress" part of my overview page.

**Comment by matryer** [comment]
Excellent feedback, thanks @alexellis
