### ISSUE TITLE
[build:7cd763a1] Search appears to be case-sensitive, which was a disappointment

### ISSUE THREAD

**Issue by seh** [pacedotdev/community#54]
I created a card with the silly title, "Wait, what is this?" (I was still trying to figure out what the main entities were.) Later, I discovered the search box in the upper right hand corner. I tried searching for "this", and nothing matched. Then I tried searching for "wait", and still nothing matched. Finally I searched for "Wait" (note the capital 'w'), and my card came up as the lone match.

Perhaps "this" is blocked as a stop word, but I expected "wait" to match "Wait". Is the search engine deliberately case-sensitive? It would be nice if we could control this, and—reaching here—perhaps use regular expressions as well. Sourcegraph offers some precedent for how to expose such options. I understand that it's not easy.

**Comment by dahernan** [comment]
I can not reproduce, `Wait` is the only none stop word there, and search is not case sensitive. Can you double check again?

<img width="550" alt="Screenshot 2020-10-08 at 09 53 18" src="https://user-images.githubusercontent.com/615811/95436804-2fdb5580-094c-11eb-8b48-cde72a0c7308.png">

**Comment by matryer** [comment]
![image](https://user-images.githubusercontent.com/101659/95471086-71cec080-0979-11eb-83bb-ffe7b99af5e3.png)
![image](https://user-images.githubusercontent.com/101659/95471099-77c4a180-0979-11eb-8f12-6fb8d7abbd12.png)
![image](https://user-images.githubusercontent.com/101659/95471120-7c895580-0979-11eb-8f91-96b2dd2c681e.png)

I also cannot reproduce this @seh - can you search again for `wait`, `Wait` and `WAIT` and let me know what happens?

**Comment by seh** [comment]
I logged out and logged in again, and now the search for "wait" (lowercase) _does_ match the card. I don't know why that's so. It occurred frequently enough last night to motivate filing the issue, but now the problem seems to be gone.

I apologize for the distraction, and thank you for making Pace.dev.

**Comment by matryer** [comment]
@seh I'm glad it's resolved but what a puzzle that is. Please don't hesitate to let us know if it happens again. 

Computers eh?
