### ISSUE TITLE
[build:883acd32] Renaming a team doesn't rename the URL slug

### ISSUE THREAD

**Issue by kinbiko** [pacedotdev/community#55]
To recreate:

- Create a team called 'abc'
- Rename the team to 'def'

Expect:

- URL is `https://pace.dev/app/$org/t/def`

Got:

- URL is `https://pace.dev/app/$org/t/abc`

**Comment by dahernan** [comment]
Sorry I though we answered this one.

At this moment the URLs for teams are inmutable, so if you rename is not going to change the URL.
The reason is we use that ID to link in other places, and is more expensive to change.

We may refactor this in the future to be less confusing

**Comment by kinbiko** [comment]
I'm happy if it's buried in your backlog somewhere. 👍
