### ISSUE TITLE
Stuff I am missing [build:883acd32] 

### ISSUE THREAD

**Issue by oderwat** [pacedotdev/community#56]
Stuff I am missing to consider it "useable" for our Teams:

* I wonder if there is a conversation list anywhere. I need an overview over all running conversations and be able to simply filter such ones which are with a single person from the team. If that's not possible we can't simply switch away from other tools.
* I also wonder where (in a Card) I can see the conversations which mention this specific card. What is the point in adding a related card to a conversation but not find this mentioned in the card itself. Especially when not seeing the conversations which are happening. I may not have the right understanding of the imagined workflow though.
* I think one should be able to search with multiple tags (as this is the only thing one can use to filter). We have for tags for clients for example. Those tell us which clients are affected by an added feature. But we also have tags like bugs. So if I want to filter for bugs of a client this is easy with our current system but seems not to be possible with pace.
* I think it should be possible to add custom fields. Without those, we can't store estimates or for example external contacts to be informed on completion.

**Comment by matryer** [comment]
Thanks @oderwat - this is very helpful.

Right now, conversations are passive but there's no reason why we can't expose more search/discovery mechanisms. Could you elaborate on how you would use Conversations in your case, and what kinds of queries would be helpful?

Card referencing is something we've been talking about. I wonder if you could expand a little on the use case? Are you mentioning cards in a Conversation? What would you expect? Would the comment be copied, or would it just say "Simon mentioned this card in _Link to conversation_"?

We are working on ways to allow people to categorise cards in whichever way suits them - but we're fighting complexity at each step; we don't want to make it easy to make a mess.

Thank you again for your feedback

**Comment by oderwat** [comment]
Thanks for your reply @matryer :)

Maybe it helps when I say that I was thinking about Pace as a replacement for a workflow that currently exists using a combination of Slack / Taiga (customized), Github, and Coda.io. I am sure it can not do "everything" and the goal would be to reduce complexity. So I guess we are in the same boat here, but maybe not. I am also more or less just brainstorming with myself right now.

We are working very closely with our clients, even integrate them in Slack and Coda. Still they usually only have a very specific (or broad) idea of what they want. So we need to distill the solution by combining their input and experience from different people in our team. This is often going for and back and also is delayed because of resources. We also only work remotely for years and of course, team members change over time. It is not uncommon that an idea which was discussed and forgotten 3 years ago creeps up again.

So one of my basic ideas is that everybody who comes "late" to a topic should be able to see what happened before he entered. This also helps with long-running discussions or paused topics, where one needs to refocus or recap what happened so far. Because of that, I use code revision, shared documents, and ticket systems pretty much since the 90s. I hate having the usual email mess with multiple CCs where you never know if somebody read it or what conversation happens behind the scene.

When I imagine using Pace I would want to see what happens in the team right now. I need to re-find topics easily. I am a great believer in "everything should be searchable" in the vein of Spotlight, locate, and Google :). But I also like to follow chains. So when I remember that there was a conversation about something I would like to be able to enter it from anywhere. The card would be the usual place: "Didn't we had a conversation about possible storage systems for this kind of data when implementing that other thing (card)?". Or "is there already a discussion about this going on (conversation list)?". Or I may start a conversation because I found that multiple cards have something in common and want, that everybody looking at the card can see this.

Afaik you already can add a card to a conversation. But I can't see the conversation from looking at the card. I imagine that all conversations which link to a card are listed when I look at the card. I would also like to have the possibility to link a conversation to another conversation. So it can branch out but you can see the hierarchy. Of course, this can become messy quickly but the reality is that it may happen anyway and is messier when I can't model it at all.

The goal and the sole reason to change from what we use now would be a better way to link topics and conversations. Currently, we use Slack channels and Github for most of our messaging, and in spite of Slack being very searchable and having threaded conversations you can't really follow along.

I am not sure if there is a good solution to all of this. After all, my ideas are not new, and a lot of systems strife to solve them. I was intrigued by the concept of Pace because of how it works so far and because of the minimalistic approach. There are tools out there which "solve everything (TM)" and also make everything worse in the end.

So far for now. I hope this is helpful.
