### ISSUE TITLE
[build:093ba6eb] interface says card not shared even though it is

### ISSUE THREAD

**Issue by awfm9** [pacedotdev/community#58]
I have just created a bunch of conversations, each with a number of related cards attached to it.

I shared each conversation with a team, which has one other member besides myself. When I go to the conversation, it still says _"NOBODY ELSE CAN SEE THIS UNTIL YOU SHARE IT."_

**Comment by dahernan** [comment]
Sorry you mean the card or the conversation?
* Cards everybody in the org could always see them
* Conversations are private to the people you share it, once you click the share button

**Comment by awfm9** [comment]
OK, that was not immediately obvious. Since the people were added successfully, I thought it was shared, too. Thanks.
