### ISSUE TITLE
[build:89d03bf8] Tour

### ISSUE THREAD

**Issue by leaanthony** [pacedotdev/community#6]
It would be great to have a tour, or some demonstrations/videos about what the workflow is/could be. Sort of a "it works like this" for newbies.

Also at high res, the screen is quite squashed. Not sure what the solution is to that though :-)
![image](https://user-images.githubusercontent.com/1943904/84348110-87182600-abf7-11ea-8a90-1de49001241a.png)

**Comment by matryer** [comment]
@leaanthony We are working on such a walkthrough/tutorial. :) 

For now, it's just:

1. Create an org
1. Create a team
1. Add some cards
1. Invite some people

The catch-22 is that the tool is better with teammates, but people want to put the tool through its paces before inviting others. We're relying on early adopters at this stage.

The answer to your gigantic screen is to use `Cmd`+`+` to zoom the page in. The other pages will fill up better. :)
