### ISSUE TITLE
Unable to delete org even after I've cancelled my description [build:1cdb8424] 

### ISSUE THREAD

**Issue by kinbiko** [pacedotdev/community#64]
I've cancelled my subscription, but the UI still tells me I have to visit the subscription page to disable my subscription before I can delete the org.

![image](https://user-images.githubusercontent.com/8797880/116779804-71cc1480-aab3-11eb-9c9c-80521c6035ab.png)

☝️ is feedback. 👇 is a request.

Please delete my `kinbiko` org.

**Comment by dahernan** [comment]
Thanks Roger, you still have some days of the billing cycle, for the cancel to be effective, that is why it doesn't allow you to delete it yet.

I'll do it for you, if that is ok, and should disappear soon.
Thanks for using it and all the feedback :)

**Comment by dahernan** [comment]
All done, it's deleted now
