### ISSUE TITLE
[build:89d03bf8] Easier setup of the Github webhook (#pace282)

### ISSUE THREAD

**Issue by pieterclaerhout** [pacedotdev/community#7]
While setting up the GitHub webhook, you are supposed to properly configure the events on which it should trigger.

I was wondering if this shouldn't be easier (it's very easy to skip one or choose the wrong one).

Can't you just let it send all events and filter on the pace.dev side? That will also make it easier if you want to add / support other events in the future.

**Comment by dahernan** [comment]
Yeah, agree is a little bit complicated, we though that github would send lots of request if we encourage to send all for everybody, but yes we can experiment to see if that is not too much

**Comment by matryer** [comment]
@pieterclaerhout That's not a bad idea... partially it comes from our desire to only ask for the data we need. We dislike services that grab all your data and you don't know what they're doing with it. But the usability angle is a fair point in this case.

**Comment by pieterclaerhout** [comment]
Being future proof is key here as well I think.

If you at some point decide to consume more events from the GitHub API, you’re already set and the user doesn’t need to change anything.

**Comment by matryer** [comment]
@dahernan I created #pace282

**Comment by matryer** [comment]
We are going to enable all events for ourselves and see if the ux needs improving before updating the docs. Thanks again for reporting @pieterclaerhout.

**Comment by matryer** [comment]
Update: We're quite happy with having all events, it seems like it is a much simpler way of enabling the integration. We've had a few bug reports on the way the integration writes comments for PRs or issues with #paceXXX mentions in the title, so we're going to address those at the same time.

**Comment by matryer** [comment]
@pieterclaerhout we've updated our endpoint to support all events, and we've simplified the advice as a result. Thanks for pointing this out.
