### ISSUE TITLE
[build:19c03d7d] Drag and drop targets are not very user friendly

### ISSUE THREAD

**Issue by fallion** [pacedotdev/community#8]
Browser: Brave (Chromium)
OS: Windows and Mac

[Screen Recording 2020-06-11 at 21.06.04.mov.zip](https://github.com/pacedotdev/community/files/4766783/Screen.Recording.2020-06-11.at.21.06.04.mov.zip)

**Comment by dahernan** [comment]
Yeah, agree, the current droppable zone, is over a card, and is difficult when you try to drop it on that space, we will try to improve it

**Comment by fallion** [comment]
Drag and drop is really fiddly. So I fully understand.

**Comment by matryer** [comment]
@fallion I did a little work on this and have made the drag areas larger (around the card). I wonder if you could have another play and let me know if that's improved or not. Be sure to do a Hard Reload (Shift+Cmd+R in Chrome) to make sure you have the latest version.

**Comment by dahernan** [comment]
Closed for now, let us know if it really works better
