### ISSUE TITLE
[build:19c03d7d] Unable to remove team

### ISSUE THREAD

**Issue by fallion** [pacedotdev/community#9]
Despite leaving the team I cannot find how to remove it.

**Comment by dahernan** [comment]
is not implemented, is on the roadmap, is more like a question of what to do with the cards/conversations created around the team, when you delete it

**Comment by matryer** [comment]
@fallion we've added a "Delete team" button on the team overview page. It is currently only visible if the team has no cards, so if you've added some to test, please delete them to reveal the button. In the future, we plan to improve this - but it should let you clear things up for now? Let us know how you get on.

**Comment by fallion** [comment]
Works! Thanks! :) Was not expecting this to get fixed so quickly.
